stages:
  - code_quality
  - test
  - build
  - deploy
  - release

.is_version_tag: &is_version_tag
  if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/'

code_quality:
  stage: code_quality
  image: python:3.12
  before_script:
    - pip install --upgrade pip
    - pip install pre-commit
    - pre-commit install
  script:
    - pre-commit run --all-files
  allow_failure: false

test_python3_8:
  stage: test
  image: python:3.8
  before_script:
    - pip install --upgrade pip
    - pip install -r requirements.txt -r requirements-dev.txt
    - pip install .
  script:
    - pytest tests/

test_python3_12:
  stage: test
  image: python:3.12
  before_script:
    - pip install --upgrade pip
    - pip install -r requirements.txt -r requirements-dev.txt
    - pip install .
  script:
    - coverage run -m pytest tests/ --junitxml=report.xml
    - coverage report
    - coverage xml -o coverage.xml
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
      junit: report.xml
  coverage: '/^TOTAL.+?(\d+\%)$/'

build:
  stage: build
  image: python:3.12
  script:
    - pip install --upgrade pip
    - pip install build
    - python -m build
  artifacts:
    paths:
      - dist/*

deploy_testpypi:
  stage: deploy
  image: python:3.12
  script:
    - pip install --upgrade pip
    - pip install twine
    - twine upload --repository-url https://test.pypi.org/legacy/ dist/* -u "__token__" -p "$PYPI_TEST_TOKEN"
  rules:
    - *is_version_tag
  needs:
    - build

deploy_pypi:
  stage: deploy
  image: python:3.12
  script:
    - pip install --upgrade pip
    - pip install twine
    - twine upload dist/* -u "__token__" -p "$PYPI_TOKEN"
  rules:
    - *is_version_tag
  needs:
    - build
  when: manual
  allow_failure: false

gitlab_release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - build
    - deploy_testpypi
  rules:
    - *is_version_tag
  script:
    - awk "/## \\[$CI_COMMIT_TAG\\]/{flag=1; next} /## \\[/{flag=0} flag" CHANGELOG.md | sed '/^$/d' > release_notes.md
  release:
    name: "Release $CI_COMMIT_TAG"
    tag_name: "$CI_COMMIT_TAG"
    description: release_notes.md
    ref: "$CI_COMMIT_SHA"
    assets:
      links:
        - name: "Pypi"
          url: "https://test.pypi.org/project/steadysun/$CI_COMMIT_TAG/"
